Create blur.cpp
Rrytel/GPU-computing pull request #4
Opened 2022-12-04 01:30 UTC by Rrytel

2022-12-18 21:18 UTC, stevenireeves commented
@Rrytel what is the issue in GenMat.cpp?

2022-12-18 21:27 UTC, stevenireeves commented on GenMat.cpp
> +     dim3 dimBlockTransA(gcd(aT.width,aT.height),gcd(aT.width,aT.height));
The block dimension is generally a tunable parameter. I'm not positive using the gcd is really how you want to do this. Also, there's no guarantee here that `dimBlockTransA.x * dimBlockTransA.y <= 1024`

2022-12-18 21:29 UTC, stevenireeves commented
For best performance you'll likely want a single kernel doing GEMM. With the computation split among many kernels you can't leverage caching.

2022-12-18 21:51 UTC, Rrytel commented
> @Rrytel what is the issue in GenMat.cpp?

I was having issues with the shared memory matrix multiplication giving incorrect values. I tried testing with the naïve kernel and the results are correct but when I make my matrices large I get just zeros

2022-12-19 04:59 UTC, stevenireeves commented on GenMat.cpp
> +  //MatMulKernel<<<dimGrid, dimBlock>>>(dA, dB, dC);
Did you mean for this to be commented out?

2022-12-19 05:06 UTC, stevenireeves commented
> > @Rrytel what is the issue in GenMat.cpp?
> 
> I was having issues with the shared memory matrix multiplication giving incorrect values. I tried testing with the naïve kernel and the results are correct but when I make my matrices large I get just zeros

In the lds kernel or simple kernel?

2022-12-19 05:14 UTC, stevenireeves commented on GenMat.cpp
> +  blockSize = gcd(AbyB.width, AbyB.height);
Again, I wouldn't use the gcd, there are instances where the gcd will be 1, and then the shared memory multiplication reduces to the naive kernel.

2022-12-19 05:46 UTC, Rrytel commented
> > > @Rrytel what is the issue in GenMat.cpp?
> > 
> > 
> > I was having issues with the shared memory matrix multiplication giving incorrect values. I tried testing with the naïve kernel and the results are correct but when I make my matrices large I get just zeros
> 
> In the lds kernel or simple kernel?

simply kernel

2022-12-19 23:50 UTC, Rrytel commented
@stevenireeves I tried the shared mem kernel and the results dont work still. I also tried using your kernel.

2022-12-20 00:02 UTC, stevenireeves commented
> @stevenireeves I tried the shared mem kernel and the results dont work still. I also tried using your kernel.

What size? The original kernel wasn't generic, it assumes the size is a multiple of blockSize.

2022-12-20 00:10 UTC, Rrytel commented
@stevenireeves 
  int N = 16;
  int M = 32;
  int K = 48;

2022-12-20 00:55 UTC, stevenireeves commented
> @stevenireeves int N = 16; int M = 32; int K = 48;

Yeah `N * K` wont be a multiple of `16 * 16`.

2022-12-20 01:30 UTC, Rrytel commented
@stevenireeves could I call the kernel on a 48x48 and check if row or col is outside the index we want for a 32x48

2022-12-20 01:39 UTC, Rrytel commented
@stevenireeves I still dont get results when N=M=K=16

2022-12-20 01:46 UTC, stevenireeves requested changes

2022-12-20 01:46 UTC, stevenireeves commented on GenMat.cpp
> +void MatMul(const CMat A, const CMat B, CMat C) {
CMat &C

2022-12-20 01:48 UTC, Rrytel commented on GenMat.cpp
> +void MatMul(const CMat A, const CMat B, CMat C) {
i dont use the matmul function. I did get results after I changed the blocksize to 16. I accidentally had it as 1 still

2022-12-20 01:48 UTC, stevenireeves commented on GenMat.cpp
> +void MatMul(const CMat A, const CMat B, CMat C) {
You'll need to pass C by reference here. In the demo it was passed by value which was invoking the copy constructor.

2022-12-20 01:50 UTC, stevenireeves commented on GenMat.cpp
> +void GEMM(const int alpha, const bool opA, const CMat A, const bool opB, const CMat B, const int beta, const CMat C, CMat D)
If you want to retain the values in D you'll still want this by Reference.

2022-12-20 01:50 UTC, stevenireeves commented on GenMat.cpp
> +void GEMM(const int alpha, const bool opA, const CMat A, const bool opB, const CMat B, const int beta, const CMat C, CMat D)
If you want to retain the values in D you'll still want this by Reference.

2022-12-20 01:51 UTC, stevenireeves commented on GenMat.cpp
> +void MatMul(const CMat A, const CMat B, CMat C) {
Make sure to remove dead code

2022-12-20 06:36 UTC, Rrytel commented
@stevenireeves do you want the mat.h and mat.cpp files to be included in the pull

2023-06-06 20:19 UTC, merged